Sc 10270/feature/update penny to use tagging
takeshape/penny pull request #145
Opened 2022-12-19 21:40 UTC by incompl

> If you don't want to invoke CI, put `[skip ci]` in the commit message

### Screenshots

### Test Plan (Steps to test):

1. 
1. 
1. 

### Checklist:

- [ ] Create a Test Plan
- [ ] Changes Communicated (in commits or above)
- [ ] Docs Updated
- [ ] Storybook Updated

2022-12-21 22:39 UTC, mshick requested changes
Looks good. Minor suggestions, and merging will be pending the CLI PR landing (should happen soon).

2022-12-21 22:39 UTC, mshick commented on scripts/prebuild.sh
> +  elif takeshape branch list | grep -q "📁 $VERCEL_GIT_COMMIT_REF (development)"; then
```suggestion
  elif takeshape branch url --name ${VERCEL_GIT_COMMIT_REF}; then
```
I think this approach is cleaner. Need this PR to land first though: https://github.com/takeshape/takeshape/pull/3813

2022-12-22 16:48 UTC, incompl commented
> Looks good. Minor suggestions, and merging will be pending the CLI PR landing (should happen soon).

@mshick I have committed your suggestions

2022-12-22 20:44 UTC, mshick commented
The CLI is updated, so I think this is good to merge.

2023-01-03 16:25 UTC, mshick approved these changes

2023-01-03 16:27 UTC, merged